name: Build and Deploy

on:
  push:
    branches:
      - page

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Page Branch
        uses: actions/checkout@v3
        with:
          ref: page

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: List output files
        run: ls -l build/

      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }} # Required for push access

      - name: Copy files to Main Branch
        run: |
          cp -a build/. .
          git config user.name 'Your Name'
          git config user.email 'your-email@example.com'
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m 'Deploy to Main Branch'
          git push
