name: Deploy Hexo Blog

on:
  push:
    branches:
      - page  # 设置触发分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: page  # 检出 page 分支的代码

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # 设置 Node.js 版本

      - name: Install and Build
        run: |
          npm install
          npm run build  
        # 运行 Hexo 构建命令

      - name: Deploy to Main Branch
        run: |
          git config --global user.name 'Hercules-Zhaoziyi' 
          git config --global user.email 'peterzhaoziyi@gmail.com' 
          git checkout -b main 
          git rm -rf .
          cp -r public/* . 
          git add .
          git commit -m "Deploy Hexo site"  
          git push -f origin main 

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 进行认证
