name: Pages

on:
  push:
    branches:
      - page # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Push to main branch
        run: |
          git config --local user.email "Hercules2005github"
          git config --local user.name "Hercules-Zhaoziyi"
          git add .
          git commit -m "Auto commit"
          git push origin main
      
