name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-artifact@v2
        with:
          name: pages
          path: ./public
  deploy:
    needs: build
    permissions:
      contents: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Main Branch
        id: deployment
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Copy Pages artifact
        run: cp -R ${{ needs.build.outputs.artifacts.pages }}/* .
      - name: Commit and Push Changes
        run: |
          git config --global user.name "Hercules-Zhaoziyi"
          git config --global user.email "peterzhaoziyi@gmail.com"
          git add .
          git commit -m "Update GitHub Pages"
          git push origin main
